resources:
  - name: MyBB
    type: GitRepo
    configuration:
      path: ~TAYLORL/pipelines-extensions
      gitProvider: myBB

  - name: myApp
    type: FileSpec
    configuration:
      sourceArtifactory: artifactoryIntegration
      pattern: "example-repo-local/myApp.sh"

  - name: myVM
    type: VmCluster
    configuration:
      sshKey: u16ssh
      targets:
        - 192.168.50.19

  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: myBuild
      buildNumber: 129

pipelines:
  - name: DeployToVM
    steps:
      - name: myDeploy
        type: tutorials/DeployApplication
        configuration:
          environmentVariables:
            # should override vm ips if present
#            DEPLOY_TARGETS: "192.168.50.3,192.168.50.4"
            # should append to vm ips
            ADDITIONAL_TARGETS: "192.168.50.18"
            # This doesn't really make sense as an api. There is no way to securely supply this except for an integration.
#            SSHKEY_INTEGRATION_NAME: "u16ssh"
          inputResources:
            - name: myVM
            - name: myApp
            - name: myBuildInfo
          targetDirectory: "/opt"
          # Artifactory removes the executable bit from files
          deployCommand: "bash ./myApp.sh"
          postDeployCommand: "echo 'this is the postDeploy command'"
          rolloutDelay: 3
#          fastFail: false
