resources:
#  - name: MyBB
#    type: GitRepo
#    configuration:
#      path: ~TAYLORL/pipelines-extensions
#      gitProvider: myBB
#
  - name: myApp
    type: FileSpec
    configuration:
      sourceArtifactory: artifactoryIntegration
      pattern: "example-repo-local/myApp.sh"

#  - name: myApp2
#    type: FileSpec
#    configuration:
#      sourceArtifactory: artifactoryIntegration
#      pattern: "example-repo-local/myApp.sh"
#
  - name: myVM
    type: VmCluster
    configuration:
      sshKey: u16ssh
      targets:
        - 192.168.50.3
        - 192.168.50.3

  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: myBuild
      buildNumber: 1

#  - name: myBuildInfo2
#    type: BuildInfo
#    configuration:
#      sourceArtifactory: artifactoryIntegration
#      buildName: myBuild2
#      buildNumber: 1

  - name: myReleaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDistro
      name: myReleaseTaylorl
      version: "1"

  - name: myReleaseBundle2
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDistro2
      name: myReleaseTaylorl
      version: "5"

pipelines:
  - name: DeployToVM
    steps:
      - name: myDeploy
        type: tutorials/DeployApplication
        configuration:
          environmentVariables:
            DEPLOY_TARGETS_OVERRIDE: "192.168.50.3,192.168.50.3"
#          nodePool: w19Taylorl
          inputResources:
            - name: myVM
#            - name: myBuildInfo
#            - name: myApp
            - name: myReleaseBundle2
          targetDirectory: "/opt/hello"
          # Artifactory removes the executable bit from files
          deployCommand: "du"
          postDeployCommand: "echo 'this is the postDeploy command'; ls"
          sshUser: root
          rolloutDelay: 3
#          fastFail: true
