resources:
  - name: MyBB
    type: GitRepo
    configuration:
      path: ~TAYLORL/pipelines-extensions
      gitProvider: myBB

  - name: MyTest
    type: tutorials/test
    configuration:
      alpha: "JFrog"
      number: 42
      flag: true

  - name: myApp
    type: FileSpec
    configuration:
      sourceArtifactory: artifactoryIntegration
      pattern: "example-repo-local/myApp.sh"

  - name: myVM
    type: VmCluster
    configuration:
      sshKey: u16ssh
      targets:
        - 192.168.50.19

pipelines:
  - name: MyHealthCheck
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"
    steps:
      - name: Health_Check_Step
        type: tutorials/HealthCheck
        configuration:
          healthCheckUrl: "https://jfrog.com"
          notifyOnSuccess: false
          notifyOnFailure: false
          stuff:
            - "This is a string"
            - "This is another string"
          inputResources:
            - name: MyTest
            - name: MyBB
  - name: DeployToVM
    steps:
      - name: myDeploy
        type: tutorials/DeployApplication
        configuration:
          environmentVariables:
            DEPLOY_TARGETS: "192.168.50.19"
            SSHKEY_INTEGRATION_NAME: "bpu18"
          inputResources:
            - name: myVM
            - name: myApp
