resources:
#  - name: MyBB
#    type: GitRepo
#    configuration:
#      path: ~TAYLORL/pipelines-extensions
#      gitProvider: myBB
#
#  - name: myApp
#    type: FileSpec
#    configuration:
#      sourceArtifactory: artifactoryIntegration
#      pattern: "example-repo-local/myApp.sh"
#
#  - name: myApp2
#    type: FileSpec
#    configuration:
#      sourceArtifactory: artifactoryIntegration
#      pattern: "example-repo-local/myApp.sh"
#
  - name: myVM
    type: VmCluster
    configuration:
      sshKey: u16ssh
      targets:
        - 192.168.50.17
#
#  - name: myBuildInfo
#    type: BuildInfo
#    configuration:
#      sourceArtifactory: artifactoryIntegration
#      buildName: myBuild
#      buildNumber: 1
#
#  - name: myBuildInfo2
#    type: BuildInfo
#    configuration:
#      sourceArtifactory: artifactoryIntegration
#      buildName: myBuild2
#      buildNumber: 1

#  - name: myReleaseBundle
#    type: ReleaseBundle
#    configuration:
#      sourceDistribution: myDistro
#      name: myReleaseTaylorl
#      version: "1"

pipelines:
  - name: DeployToVM
    steps:
      - name: myDeploy
        type: tutorials/DeployApplication
        configuration:
#          nodePool: w19Taylorl
#          inputResources:
            - name: myVM
#            - name: myApp
#            - name: myApp2
#            - name: myBuildInfo
#            - name: myBuildInfo2
#            - name: myReleaseBundle
          targetDirectory: "/opt"
          # Artifactory removes the executable bit from files
          deployCommand: "du"
          postDeployCommand: "echo 'this is the postDeploy command'; ls"
#          fastFail: false
