resources:
  - name: MyBB
    type: GitRepo
    configuration:
      path: ~TAYLORL/pipelines-extensions
      gitProvider: myBB

  - name: MyMVNBuildBB
    type: GitRepo
    configuration:
      path: ~TAYLORL/maven-hello-world
      gitProvider: myBB

  - name: myApp
    type: FileSpec
    configuration:
      sourceArtifactory: artifactoryIntegration
      pattern: "example-repo-local/myApp.sh"

  - name: myVM
    type: VmCluster
    configuration:
      sshKey: u16ssh
      targets:
        - 192.168.50.19
        - 192.168.50.18

  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: myBuildInfo
      buildNumber: 1

  - name: myReleaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDistro
      name: myReleaseTaylorl
      version: "1"

pipelines:
  - name: DeployToVM
    steps:
      - name: myDeploy
        type: tutorials/DeployApplication
        configuration:
          inputResources:
            - name: myVM
            - name: myApp
            - name: myBuildInfo
            - name: myReleaseBundle
          targetDirectory: "/opt"
          # Artifactory removes the executable bit from files
          deployCommand: "du"
          postDeployCommand: "echo 'this is the postDeploy command'; ls"
          rolloutDelay: 3
#          fastFail: false
