resources:
  - name: MyBB
    type: GitRepo
    configuration:
      path: ~TAYLORL/pipelines-extensions
      gitProvider: myBB

  - name: myApp
    type: FileSpec
    configuration:
      sourceArtifactory: artifactoryIntegration
      pattern: "example-repo-local/myApp.sh"

  - name: myVM
    type: VmCluster
    configuration:
      sshKey: u16ssh
      targets:
        - 192.168.50.16
        - 192.168.50.19
        - 192.168.50.19
        - 192.168.50.19

pipelines:
  - name: DeployToVM
    steps:
      - name: myDeploy
        type: tutorials/DeployApplication
        configuration:
          environmentVariables:
            # should override vm ips if present
            DEPLOY_TARGETS: "192.168.50.3,192.168.50.4"
            # should append to vm ips
            ADDITIONAL_TARGETS: "192.168.50.42"
            SSHKEY_INTEGRATION_NAME: "u16ssh"
          inputResources:
            - name: myVM
            - name: myApp
          targetDirectory: "/opt"
          # Artifactory removes the executable bit from files
          deployCommand: "bash ./myApp.sh"
          rolloutDelay: 3
          fastFail: false
