resources:
  - name: MyBB
    type: GitRepo
    configuration:
      path: ~TAYLORL/pipelines-extensions
      gitProvider: myBB

  - name: MyMVNBuildBB
    type: GitRepo
    configuration:
      path: ~TAYLORL/maven-hello-world
      gitProvider: myBB

  - name: MyMVNBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: myMVNBuild
      buildNumber: 1
      externalCI: jenkinsIntegration

  - name: myApp
    type: FileSpec
    configuration:
      sourceArtifactory: artifactoryIntegration
      pattern: "example-repo-local/myApp.sh"

  - name: myVM
    type: VmCluster
    configuration:
      sshKey: u16ssh
      targets:
        - 192.168.50.19
        - 192.168.50.18

  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: myBuild
      buildNumber: 129

pipelines:
  - name: DeployToVM
    steps:
      - name: myDeploy
        type: tutorials/DeployApplication
        configuration:
          inputResources:
            - name: myVM
            - name: myApp
            - name: myBuildInfo
          targetDirectory: "/opt"
          # Artifactory removes the executable bit from files
          deployCommand: "bash ./myApp.sh"
          postDeployCommand: "echo 'this is the postDeploy command'"
          rolloutDelay: 3
#          fastFail: false
  - name: buildGoModule
    steps:
      - name: buildGo
        type: GoBuild
        configuration:
          autoPublishBuildInfo: true
          integrations:
            - name: artifactoryIntegration
          inputResources:
            - name: MyMVNBuildBB         # required
          outputResources:
            - name: MyMVNBuildInfo

